-- Setup NOAA GSOD External Table and Stage
-- Prerequisites: Run 00_create_database.sql FIRST!
-- This creates a stage and external table pointing to public NOAA S3 bucket

-- Set context
USE DATABASE HYPERLOGISTICS_DB;
USE SCHEMA BRONZE;

-- Step 1: Recreate stage WITHOUT storage integration (public bucket = anonymous access)
CREATE OR REPLACE STAGE HYPERLOGISTICS_DB.BRONZE.NOAA_S3_STAGE
    URL = 's3://noaa-gsod-pds/'
    FILE_FORMAT = (TYPE = CSV SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"');

-- Step 2: Verify listing works (should return ~1 file quickly)
LIST @HYPERLOGISTICS_DB.BRONZE.NOAA_S3_STAGE/2023/01001099999.csv;

-- 2. Create NOAA GSOD External Table pointing to the stage
-- Columns mapped by position ($1..$28) matching actual NOAA GSOD CSV schema.
-- PARTITION BY DATA_YEAR enables fast queries scoped to a single year folder.
CREATE OR REPLACE EXTERNAL TABLE BRONZE.NOAA_GSOD (
    STATION          VARCHAR AS (VALUE:c1::VARCHAR),
    DATE             DATE    AS (TRY_TO_DATE(VALUE:c2::VARCHAR, 'MM/DD/YYYY')),
    LATITUDE         FLOAT   AS (TRY_TO_DOUBLE(VALUE:c3::VARCHAR)),
    LONGITUDE        FLOAT   AS (TRY_TO_DOUBLE(VALUE:c4::VARCHAR)),
    ELEVATION        FLOAT   AS (TRY_TO_DOUBLE(VALUE:c5::VARCHAR)),
    NAME             VARCHAR AS (VALUE:c6::VARCHAR),
    TEMP             FLOAT   AS (TRY_TO_DOUBLE(VALUE:c7::VARCHAR)),
    TEMP_ATTRIBUTES  INT     AS (TRY_TO_NUMBER(VALUE:c8::VARCHAR)),
    DEWP             FLOAT   AS (TRY_TO_DOUBLE(VALUE:c9::VARCHAR)),
    DEWP_ATTRIBUTES  INT     AS (TRY_TO_NUMBER(VALUE:c10::VARCHAR)),
    SLP              FLOAT   AS (TRY_TO_DOUBLE(VALUE:c11::VARCHAR)),
    SLP_ATTRIBUTES   INT     AS (TRY_TO_NUMBER(VALUE:c12::VARCHAR)),
    STP              FLOAT   AS (TRY_TO_DOUBLE(VALUE:c13::VARCHAR)),
    STP_ATTRIBUTES   INT     AS (TRY_TO_NUMBER(VALUE:c14::VARCHAR)),
    VISIB            FLOAT   AS (TRY_TO_DOUBLE(VALUE:c15::VARCHAR)),
    VISIB_ATTRIBUTES INT     AS (TRY_TO_NUMBER(VALUE:c16::VARCHAR)),
    WDSP             FLOAT   AS (TRY_TO_DOUBLE(VALUE:c17::VARCHAR)),
    WDSP_ATTRIBUTES  INT     AS (TRY_TO_NUMBER(VALUE:c18::VARCHAR)),
    MXSPD            FLOAT   AS (TRY_TO_DOUBLE(VALUE:c19::VARCHAR)),
    GUST             FLOAT   AS (TRY_TO_DOUBLE(VALUE:c20::VARCHAR)),
    MAX              FLOAT   AS (TRY_TO_DOUBLE(VALUE:c21::VARCHAR)),
    MAX_ATTRIBUTES   VARCHAR AS (VALUE:c22::VARCHAR),
    MIN              FLOAT   AS (TRY_TO_DOUBLE(VALUE:c23::VARCHAR)),
    MIN_ATTRIBUTES   VARCHAR AS (VALUE:c24::VARCHAR),
    PRCP             FLOAT   AS (TRY_TO_DOUBLE(VALUE:c25::VARCHAR)),
    PRCP_ATTRIBUTES  VARCHAR AS (VALUE:c26::VARCHAR),
    SNDP             FLOAT   AS (TRY_TO_DOUBLE(VALUE:c27::VARCHAR)),
    FRSHTT           VARCHAR AS (VALUE:c28::VARCHAR)
)
LOCATION = @HYPERLOGISTICS_DB.BRONZE.NOAA_S3_STAGE
FILE_FORMAT = (TYPE = CSV SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"')
AUTO_REFRESH = FALSE;

-- Verify
-- LIST @HYPERLOGISTICS_DB.BRONZE.NOAA_S3_STAGE/2023/;


--  Verify — should return real station IDs, dates, temperatures
-- SELECT STATION, DATE, TEMP, PRCP, VISIB
-- FROM BRONZE.NOAA_GSOD
-- WHERE METADATA$FILENAME LIKE '2023/01001099999.csv'