-- Setup NOAA GSOD external table
-- Run this in Snowflake Worksheet

CREATE OR REPLACE EXTERNAL TABLE BRONZE.NOAA_GSOD (
    STATION STRING,
    DATE DATE,
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    ELEVATION FLOAT,
    NAME STRING,
    TEMP FLOAT,
    TEMP_ATTRIBUTES INT,
    DEWP FLOAT,
    DEWP_ATTRIBUTES INT,
    SLP FLOAT,
    SLP_ATTRIBUTES INT,
    STP FLOAT,
    STP_ATTRIBUTES INT,
    VISIB FLOAT,
    VISIB_ATTRIBUTES INT,
    WDSP FLOAT,
    WDSP_ATTRIBUTES INT,
    MXSPD FLOAT,
    GUST FLOAT,
    MAX FLOAT,
    MAX_ATTRIBUTES STRING,
    MIN FLOAT,
    MIN_ATTRIBUTES STRING,
    PRCP FLOAT,
    PRCP_ATTRIBUTES STRING,
    SNDP FLOAT,
    FRSHTT STRING
)
LOCATION = @NOAA_S3_STAGE
FILE_FORMAT = (TYPE = PARQUET)
AUTO_REFRESH = TRUE;