-- Setup NOAA GSOD External Table and Stage
-- Prerequisites: Run 00_create_database.sql FIRST!
-- This creates a stage and external table pointing to public NOAA S3 bucket

-- Set context
USE DATABASE HYPERLOGISTICS_DB;
USE SCHEMA BRONZE;

-- 1. First, create the S3 stage for NOAA data (public bucket)
CREATE OR REPLACE STAGE HYPERLOGISTICS_DB.BRONZE.NOAA_S3_STAGE
URL = 's3://noaa-gsod-pds/'  -- Public NOAA bucket
FILE_FORMAT = (TYPE = PARQUET);

-- 2. Create NOAA GSOD External Table pointing to the stage
CREATE OR REPLACE EXTERNAL TABLE BRONZE.NOAA_GSOD (
    STATION STRING AS (VALUE:STATION::VARCHAR),
    DATE DATE AS (VALUE:DATE::DATE),
    LATITUDE FLOAT AS (VALUE:LATITUDE::FLOAT),
    LONGITUDE FLOAT AS (VALUE:LONGITUDE::FLOAT),
    ELEVATION FLOAT AS (VALUE:ELEVATION::FLOAT),
    NAME STRING AS (VALUE:NAME::VARCHAR),
    TEMP FLOAT AS (VALUE:TEMP::FLOAT),
    TEMP_ATTRIBUTES INT AS (VALUE:TEMP_ATTRIBUTES::INT),
    DEWP FLOAT AS (VALUE:DEWP::FLOAT),
    DEWP_ATTRIBUTES INT AS (VALUE:DEWP_ATTRIBUTES::INT),
    SLP FLOAT AS (VALUE:SLP::FLOAT),
    SLP_ATTRIBUTES INT AS (VALUE:SLP_ATTRIBUTES::INT),
    STP FLOAT AS (VALUE:STP::FLOAT),
    STP_ATTRIBUTES INT AS (VALUE:STP_ATTRIBUTES::INT),
    VISIB FLOAT AS (VALUE:VISIB::FLOAT),
    VISIB_ATTRIBUTES INT AS (VALUE:VISIB_ATTRIBUTES::INT),
    WDSP FLOAT AS (VALUE:WDSP::FLOAT),
    WDSP_ATTRIBUTES INT AS (VALUE:WDSP_ATTRIBUTES::INT),
    MXSPD FLOAT AS (VALUE:MXSPD::FLOAT),
    GUST FLOAT AS (VALUE:GUST::FLOAT),
    MAX FLOAT AS (VALUE:MAX::FLOAT),
    MAX_ATTRIBUTES STRING AS (VALUE:MAX_ATTRIBUTES::VARCHAR),
    MIN FLOAT AS (VALUE:MIN::FLOAT),
    MIN_ATTRIBUTES STRING AS (VALUE:MIN_ATTRIBUTES::VARCHAR),
    PRCP FLOAT AS (VALUE:PRCP::FLOAT),
    PRCP_ATTRIBUTES STRING AS (VALUE:PRCP_ATTRIBUTES::VARCHAR),
    SNDP FLOAT AS (VALUE:SNDP::FLOAT),
    FRSHTT STRING AS (VALUE:FRSHTT::VARCHAR)
)
LOCATION = @HYPERLOGISTICS_DB.BRONZE.NOAA_S3_STAGE
FILE_FORMAT = (TYPE = PARQUET)
AUTO_REFRESH = TRUE;